# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('theatre', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_path', models.FilePathField(path='images/')),
                ('reseration', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
