# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consert',
            old_name='reseration',
            new_name='reservation',
        ),
    ]
