# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20161213_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consert',
            old_name='desc',
            new_name='description',
        ),
    ]
