# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20161213_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consert',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 13, 11, 32, 6, 465021, tzinfo=utc)),
        ),
    ]
