# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20161213_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consert',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
